cloud_provider: "groq"
llm_model: "llama-3.1-70b-versatile"
embedding_model: "mxbai-embed-large"

token_limit: 1000
target_words: 200
chunk_flexbility: 0.25

n_clusters: 13
embed_batch_size: 20
n_closest_representatives: 1
